services:
  message-manager:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./media:/app/media
      - ./metadata.json:/app/metadata.json
    environment:
      - ADMIN_PASSWORD=hca123
    restart: always
